// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 unxed

//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
	"text/template"
)

type fastPattern struct {
	Name      string
	MinInts   int
	MaxInts   int
	NumFloats int
	FloatBits int
	Layout    string
}

var patterns = []fastPattern{
	{Name: "IntOnly", MaxInts: 15, NumFloats: 0},
	{Name: "TrailingFloat32x1", MaxInts: 15, NumFloats: 1, FloatBits: 32, Layout: "trailing"},
	{Name: "TrailingFloat64x1", MaxInts: 15, NumFloats: 1, FloatBits: 64, Layout: "trailing"},
	{Name: "InterleavedFloat32x1", MinInts: 1, MaxInts: 15, NumFloats: 1, FloatBits: 32, Layout: "interleaved"},
}

func main() {
	var buf bytes.Buffer
	execTemplate(&buf, "header", tmplHeader, nil)
	emitWrappers(&buf)
	emitDispatch(&buf)
	emitInterleavedFloat32x1(&buf)
	execTemplate(&buf, "tryRegister", tmplTryRegisterFastPath, nil)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("gofmt: %v\n%s", err, buf.String())
	}
	if err := os.WriteFile("zz_fast_func.go", src, 0644); err != nil {
		log.Fatal(err)
	}
}

var funcs = template.FuncMap{
	"seq": func(n int) []int {
		s := make([]int, n)
		for i := range s {
			s[i] = i
		}
		return s
	},
	"add": func(a, b int) int { return a + b },
	"argList": func(n int) string {
		if n == 0 {
			return ""
		}
		var parts []string
		for i := 0; i < n; i++ {
			parts = append(parts, fmt.Sprintf("a%d uintptr", i+1))
		}
		return strings.Join(parts, ", ")
	},
}

func execTemplate(buf *bytes.Buffer, name, text string, data any) {
	t := template.Must(template.New(name).Funcs(funcs).Parse(text))
	if err := t.Execute(buf, data); err != nil {
		log.Fatalf("template %s: %v", name, err)
	}
}

var tmplHeader = `// Code generated by genfastfunc.go; DO NOT EDIT.

// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 unxed

//go:build (amd64 || arm64) && (darwin || freebsd || linux || netbsd) && !windows

package purego

import (
	"math"
	"reflect"
	"runtime"
	"sync"
	"unsafe"

	"github.com/go-webgpu/goffi/ffi"
	"github.com/go-webgpu/goffi/types"
)

func forceFuncPtr(dst reflect.Value, src any) {
	dstPtr := dst.Addr().UnsafePointer()
	srcPtr := (*unsafe.Pointer)(reflect.ValueOf(src).UnsafePointer())
	*(*unsafe.Pointer)(dstPtr) = *srcPtr
}

type fastCallContext struct {
	ints   [15]uintptr
	floats [8]uintptr
	args   [23]unsafe.Pointer
	ret    uintptr
}

var fastCallPool = sync.Pool{
	New: func() any {
		return &fastCallContext{}
	},
}

func fastCallIF(cif *types.CallInterface, cfn uintptr, ints [15]uintptr, floats [8]uintptr) uintptr {
	ctx := fastCallPool.Get().(*fastCallContext)
	ctx.ints = ints
	ctx.floats = floats

	var argIdx, iIdx, fIdx int
	for _, t := range cif.ArgTypes {
		if t.Kind == types.FloatType || t.Kind == types.DoubleType {
			ctx.args[argIdx] = unsafe.Pointer(&ctx.floats[fIdx])
			fIdx++
		} else {
			ctx.args[argIdx] = unsafe.Pointer(&ctx.ints[iIdx])
			iIdx++
		}
		argIdx++
	}

	ctx.ret = 0
	_, _ = ffi.CallFunction(cif, unsafe.Pointer(cfn), unsafe.Pointer(&ctx.ret), ctx.args[:argIdx])
	ret := ctx.ret
	fastCallPool.Put(ctx)
	return ret
}
`

// maxPointerMaskArgs bounds the integer argument counts for which a wrapper is
// generated for every mix of pointer and non-pointer arguments: that is 2^n
// instantiations per count. Longer signatures with a pointer among their
// arguments take the reflect path; without one they still get a fast wrapper.
const maxPointerMaskArgs = 6

var tmplFastWord = `
// fastWord is the type of an integer-class argument of a fast wrapper.
//
// The wrapper is installed under the registered function's own type
// (forceFuncPtr), so its parameters must match that type slot for slot in
// the GC's eyes: a pointer argument has to arrive as a pointer, or the GC
// neither keeps its object alive for the duration of the C call nor adjusts
// it when the stack moves. Each wrapper below is therefore generic over
// uintptr and unsafe.Pointer per argument, and tryRegisterFastPath picks the
// instantiation whose pointer slots match the registered signature.
type fastWord interface{ uintptr | unsafe.Pointer }
`

// emitWrappers writes one generic wrapper per integer argument count, float
// suffix and return shape: fastInts{N}{Float}{R|V}.
func emitWrappers(buf *bytes.Buffer) {
	buf.WriteString(tmplFastWord)
	for _, bits := range []int{0, 32, 64} {
		maxInts := 15
		if bits != 0 {
			maxInts = 14
		}
		for n := 0; n <= maxInts; n++ {
			for _, ret := range []bool{true, false} {
				emitWrapper(buf, n, bits, ret)
			}
		}
	}
}

func wrapperName(n, bits int, ret bool) string {
	name := fmt.Sprintf("fastInts%d", n)
	if bits != 0 {
		name += fmt.Sprintf("F%d", bits)
	}
	if ret {
		return name + "R"
	}
	return name + "V"
}

func emitWrapper(buf *bytes.Buffer, n, bits int, ret bool) {
	var typeParams, params []string
	for i := 1; i <= n; i++ {
		typeParams = append(typeParams, fmt.Sprintf("A%d", i))
		params = append(params, fmt.Sprintf("a%d A%d", i, i))
	}
	if bits != 0 {
		params = append(params, fmt.Sprintf("f1 float%d", bits))
	}
	tp := ""
	if n > 0 {
		tp = "[" + strings.Join(typeParams, ", ") + " fastWord]"
	}
	result := ""
	if ret {
		result = " uintptr"
	}
	fmt.Fprintf(buf, "\nfunc %s%s(fn reflect.Value, cif *types.CallInterface, cfn uintptr) {\n", wrapperName(n, bits, ret), tp)
	fmt.Fprintf(buf, "\timpl := func(%s)%s {\n", strings.Join(params, ", "), result)
	buf.WriteString("\t\tvar ints [15]uintptr\n")
	for i := 1; i <= n; i++ {
		fmt.Fprintf(buf, "\t\tints[%d] = uintptr(a%d)\n", i-1, i)
	}
	buf.WriteString("\t\tvar floats [8]uintptr\n")
	if bits != 0 {
		fmt.Fprintf(buf, "\t\tfloats[0] = uintptr(math.Float%dbits(f1))\n", bits)
	}
	if ret {
		buf.WriteString("\t\tr := fastCallIF(cif, cfn, ints, floats)\n")
	} else {
		buf.WriteString("\t\tfastCallIF(cif, cfn, ints, floats)\n")
	}
	for i := 1; i <= n; i++ {
		fmt.Fprintf(buf, "\t\truntime.KeepAlive(a%d)\n", i)
	}
	if ret {
		buf.WriteString("\t\treturn r\n")
	}
	buf.WriteString("\t}\n\tforceFuncPtr(fn, &impl)\n}\n")
}

// emitDispatch writes registerFastFunc, which picks the wrapper instantiation
// for an argument count, a pointer mask (bit i set: integer argument i is a
// pointer), a trailing float width (0 for none) and a return shape.
func emitDispatch(buf *bytes.Buffer) {
	buf.WriteString(`
// registerFastFunc sets fn to a zero-allocation wrapper whose parameter types
// match the registered signature, and reports whether one was generated for
// it. See fastWord.
func registerFastFunc(fn reflect.Value, cif *types.CallInterface, cfn uintptr, numInts int, ptrMask uint32, floatBits int, hasReturn bool) bool {
	switch floatBits {
`)
	for _, bits := range []int{0, 32, 64} {
		maxInts := 15
		if bits != 0 {
			maxInts = 14
		}
		fmt.Fprintf(buf, "\tcase %d:\n\t\tswitch numInts {\n", bits)
		for n := 0; n <= maxInts; n++ {
			fmt.Fprintf(buf, "\t\tcase %d:\n\t\t\tswitch ptrMask {\n", n)
			masks := 1
			if n <= maxPointerMaskArgs {
				masks = 1 << n
			}
			for mask := 0; mask < masks; mask++ {
				var targs []string
				for i := 0; i < n; i++ {
					if mask&(1<<i) != 0 {
						targs = append(targs, "unsafe.Pointer")
					} else {
						targs = append(targs, "uintptr")
					}
				}
				inst := ""
				if n > 0 {
					inst = "[" + strings.Join(targs, ", ") + "]"
				}
				fmt.Fprintf(buf, "\t\t\tcase %d:\n\t\t\t\tif hasReturn {\n\t\t\t\t\t%s%s(fn, cif, cfn)\n\t\t\t\t} else {\n\t\t\t\t\t%s%s(fn, cif, cfn)\n\t\t\t\t}\n\t\t\t\treturn true\n",
					mask, wrapperName(n, bits, true), inst, wrapperName(n, bits, false), inst)
			}
			buf.WriteString("\t\t\t}\n")
		}
		buf.WriteString("\t\t}\n")
	}
	buf.WriteString("\t}\n\treturn false\n}\n")
}

var tmplInterleavedFloat = `func registerFastFuncInterleavedFloat32x1(fn reflect.Value, cif *types.CallInterface, cfn uintptr, totalArgs, floatPos int, hasReturn bool) {
	switch totalArgs {
{{- range .}}
	case {{.TotalArgs}}:
		switch floatPos {
{{- range .Cases}}
		case {{.FloatPos}}:
			if hasReturn {
				impl := func({{.Params}}) uintptr {
					var ints [15]uintptr
					{{- range $i := seq .NumInts}}
					ints[{{$i}}] = a{{add $i 1}}
					{{- end}}
					var floats [8]uintptr
					floats[0] = uintptr(math.Float32bits(f1))
					return fastCallIF(cif, cfn, ints, floats)
				}
				forceFuncPtr(fn, &impl)
			} else {
				impl := func({{.Params}}) {
					var ints [15]uintptr
					{{- range $i := seq .NumInts}}
					ints[{{$i}}] = a{{add $i 1}}
					{{- end}}
					var floats [8]uintptr
					floats[0] = uintptr(math.Float32bits(f1))
					fastCallIF(cif, cfn, ints, floats)
				}
				forceFuncPtr(fn, &impl)
			}
{{- end}}
		}
{{- end}}
	}
}
`

func emitInterleavedFloat32x1(buf *bytes.Buffer) {
	type caseData struct {
		FloatPos int
		Params   string
		NumInts  int
	}
	type totalData struct {
		TotalArgs int
		Cases     []caseData
	}
	var groups []totalData
	for totalArgs := 2; totalArgs <= 15; totalArgs++ {
		var cases []caseData
		for floatPos := 0; floatPos <= totalArgs-2; floatPos++ {
			var parts []string
			intIdx := 1
			for i := 0; i < totalArgs; i++ {
				if i == floatPos {
					parts = append(parts, "f1 float32")
				} else {
					parts = append(parts, fmt.Sprintf("a%d uintptr", intIdx))
					intIdx++
				}
			}
			cases = append(cases, caseData{
				FloatPos: floatPos,
				Params:   strings.Join(parts, ", "),
				NumInts:  totalArgs - 1,
			})
		}
		groups = append(groups, totalData{TotalArgs: totalArgs, Cases: cases})
	}
	execTemplate(buf, "interleaved", tmplInterleavedFloat, groups)
}

var tmplTryRegisterFastPath = `func tryRegisterFastPath(fn reflect.Value, cif *types.CallInterface, cfn uintptr, ty reflect.Type) bool {
	if !((runtime.GOARCH == "amd64" || runtime.GOARCH == "arm64") && runtime.GOOS != "windows") {
		return false
	}
	numIn := ty.NumIn()
	if numIn > 15 {
		return false
	}

	var numFloats, numInts int
	var ptrMask uint32
	trailingFloats := true
	seenFloat := false
	floatPos := -1

	for i := 0; i < numIn; i++ {
		switch ty.In(i).Kind() {
		// The fast wrappers take every integer argument as a uintptr, and
		// forceFuncPtr installs them under fn's own type. Go's register ABI
		// lets the callee spill its register arguments into a spill area the
		// caller reserves and lays out from the declared type, so the two
		// layouts must agree slot for slot. A narrower argument (int32, bool,
		// ...) packs tighter in the caller's area than a uintptr does in the
		// wrapper's: the wrapper then spills past the end of that area over
		// the caller's own frame, and the GC later finds an integer where the
		// caller keeps a pointer ("invalid pointer found on stack"). Only
		// pointer-sized arguments share the layout, so anything narrower
		// takes the reflect path.
		case reflect.Uintptr, reflect.Uint, reflect.Uint64,
			reflect.Int, reflect.Int64,
			reflect.Pointer, reflect.UnsafePointer:
			if seenFloat {
				trailingFloats = false
			}
			if k := ty.In(i).Kind(); k == reflect.Pointer || k == reflect.UnsafePointer {
				ptrMask |= 1 << numInts
			}
			numInts++
		case reflect.Float32, reflect.Float64:
			if !seenFloat {
				floatPos = i
			}
			seenFloat = true
			numFloats++
		default:
			return false // Fallback for Structs, Arrays, Strings, Slices
		}
	}
	if numFloats > 8 || numInts > 15 {
		return false
	}

	hasReturn := ty.NumOut() > 0
	if hasReturn {
		switch ty.Out(0).Kind() {
		case reflect.Uintptr, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
			reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Bool, reflect.Pointer, reflect.UnsafePointer:
		case reflect.Float32, reflect.Float64:
			return false // Fast wrappers return uintptr, which uses a different ABI register class.
		default:
			return false
		}
	}

	if numFloats == 0 {
		return registerFastFunc(fn, cif, cfn, numInts, ptrMask, 0, hasReturn)
	}
	if numFloats == 1 && trailingFloats && ty.In(numInts).Kind() == reflect.Float32 {
		return registerFastFunc(fn, cif, cfn, numInts, ptrMask, 32, hasReturn)
	}
	if numFloats == 1 && trailingFloats && ty.In(numInts).Kind() == reflect.Float64 {
		return registerFastFunc(fn, cif, cfn, numInts, ptrMask, 64, hasReturn)
	}
	// The interleaved wrappers take every integer argument as a uintptr, so
	// they only fit signatures without pointers (see fastWord).
	if numFloats == 1 && !trailingFloats && ptrMask == 0 && ty.In(floatPos).Kind() == reflect.Float32 {
		registerFastFuncInterleavedFloat32x1(fn, cif, cfn, numIn, floatPos, hasReturn)
		return true
	}

	return false
}
`
