// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 unxed

//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
	"text/template"
)

type fastPattern struct {
	Name      string
	MinInts   int
	MaxInts   int
	NumFloats int
	FloatBits int
	Layout    string
}

var patterns = []fastPattern{
	{Name: "IntOnly", MaxInts: 15, NumFloats: 0},
	{Name: "TrailingFloat32x1", MaxInts: 15, NumFloats: 1, FloatBits: 32, Layout: "trailing"},
	{Name: "TrailingFloat64x1", MaxInts: 15, NumFloats: 1, FloatBits: 64, Layout: "trailing"},
	{Name: "InterleavedFloat32x1", MinInts: 1, MaxInts: 15, NumFloats: 1, FloatBits: 32, Layout: "interleaved"},
}

func main() {
	var buf bytes.Buffer
	execTemplate(&buf, "header", tmplHeader, nil)
	emitIntOnly(&buf)
	emitTrailingFloat(&buf, 32)
	emitTrailingFloat(&buf, 64)
	emitInterleavedFloat32x1(&buf)
	execTemplate(&buf, "tryRegister", tmplTryRegisterFastPath, nil)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("gofmt: %v\n%s", err, buf.String())
	}
	if err := os.WriteFile("zz_fast_func.go", src, 0644); err != nil {
		log.Fatal(err)
	}
}

var funcs = template.FuncMap{
	"seq": func(n int) []int {
		s := make([]int, n)
		for i := range s {
			s[i] = i
		}
		return s
	},
	"add": func(a, b int) int { return a + b },
	"argList": func(n int) string {
		if n == 0 {
			return ""
		}
		var parts []string
		for i := 0; i < n; i++ {
			parts = append(parts, fmt.Sprintf("a%d uintptr", i+1))
		}
		return strings.Join(parts, ", ")
	},
}

func execTemplate(buf *bytes.Buffer, name, text string, data any) {
	t := template.Must(template.New(name).Funcs(funcs).Parse(text))
	if err := t.Execute(buf, data); err != nil {
		log.Fatalf("template %s: %v", name, err)
	}
}

var tmplHeader = `// Code generated by genfastfunc.go; DO NOT EDIT.

// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 unxed

//go:build (amd64 || arm64) && (darwin || freebsd || linux || netbsd) && !windows

package purego

import (
	"math"
	"reflect"
	"runtime"
	"sync"
	"unsafe"

	"github.com/go-webgpu/goffi/ffi"
	"github.com/go-webgpu/goffi/types"
)

func forceFuncPtr(dst reflect.Value, src any) {
	dstPtr := dst.Addr().UnsafePointer()
	srcPtr := (*unsafe.Pointer)(reflect.ValueOf(src).UnsafePointer())
	*(*unsafe.Pointer)(dstPtr) = *srcPtr
}

type fastCallContext struct {
	ints   [15]uintptr
	floats [8]uintptr
	args   [23]unsafe.Pointer
	ret    uintptr
}

var fastCallPool = sync.Pool{
	New: func() any {
		return &fastCallContext{}
	},
}

func fastCallIF(cif *types.CallInterface, cfn uintptr, ints [15]uintptr, floats [8]uintptr) uintptr {
	ctx := fastCallPool.Get().(*fastCallContext)
	ctx.ints = ints
	ctx.floats = floats

	var argIdx, iIdx, fIdx int
	for _, t := range cif.ArgTypes {
		if t.Kind == types.FloatType || t.Kind == types.DoubleType {
			ctx.args[argIdx] = unsafe.Pointer(&ctx.floats[fIdx])
			fIdx++
		} else {
			ctx.args[argIdx] = unsafe.Pointer(&ctx.ints[iIdx])
			iIdx++
		}
		argIdx++
	}

	ctx.ret = 0
	_, _ = ffi.CallFunction(cif, unsafe.Pointer(cfn), unsafe.Pointer(&ctx.ret), ctx.args[:argIdx])
	ret := ctx.ret
	fastCallPool.Put(ctx)
	return ret
}
`

var tmplIntOnly = `// registerFastFunc sets fn to a zero-allocation closure
func registerFastFunc(fn reflect.Value, cif *types.CallInterface, cfn uintptr, numArgs int, hasReturn bool) {
	switch numArgs {
{{- range .}}
	case {{.N}}:
		if hasReturn {
			impl := func({{.Params}}) uintptr {
				var ints [15]uintptr
				{{- range $i := seq .N}}
				ints[{{$i}}] = a{{add $i 1}}
				{{- end}}
				var floats [8]uintptr
				return fastCallIF(cif, cfn, ints, floats)
			}
			forceFuncPtr(fn, &impl)
		} else {
			impl := func({{.Params}}) {
				var ints [15]uintptr
				{{- range $i := seq .N}}
				ints[{{$i}}] = a{{add $i 1}}
				{{- end}}
				var floats [8]uintptr
				fastCallIF(cif, cfn, ints, floats)
			}
			forceFuncPtr(fn, &impl)
		}
{{- end}}
	}
}
`

func emitIntOnly(buf *bytes.Buffer) {
	type caseData struct {
		N      int
		Params string
	}
	var cases []caseData
	for n := 0; n <= 15; n++ {
		cases = append(cases, caseData{N: n, Params: funcs["argList"].(func(int) string)(n)})
	}
	execTemplate(buf, "intOnly", tmplIntOnly, cases)
}

var tmplTrailingFloat = `// registerFastFuncFloat{{.Bits}}x1 handles N int args + 1 trailing float.
func registerFastFuncFloat{{.Bits}}x1(fn reflect.Value, cif *types.CallInterface, cfn uintptr, numInts int, hasReturn bool) {
	switch numInts {
{{- range .Cases}}
	case {{.N}}:
		if hasReturn {
			impl := func({{.Params}}{{if .Params}}, {{end}}f1 float{{$.Bits}}) uintptr {
				var ints [15]uintptr
				{{- range $i := seq .N}}
				ints[{{$i}}] = a{{add $i 1}}
				{{- end}}
				var floats [8]uintptr
				floats[0] = uintptr(math.Float{{$.Bits}}bits(f1))
				return fastCallIF(cif, cfn, ints, floats)
			}
			forceFuncPtr(fn, &impl)
		} else {
			impl := func({{.Params}}{{if .Params}}, {{end}}f1 float{{$.Bits}}) {
				var ints [15]uintptr
				{{- range $i := seq .N}}
				ints[{{$i}}] = a{{add $i 1}}
				{{- end}}
				var floats [8]uintptr
				floats[0] = uintptr(math.Float{{$.Bits}}bits(f1))
				fastCallIF(cif, cfn, ints, floats)
			}
			forceFuncPtr(fn, &impl)
		}
{{- end}}
	}
}
`

func emitTrailingFloat(buf *bytes.Buffer, bits int) {
	type caseData struct {
		N      int
		Params string
	}
	type rootData struct {
		Bits  int
		Cases []caseData
	}
	var cases []caseData
	for n := 0; n <= 14; n++ {
		cases = append(cases, caseData{N: n, Params: funcs["argList"].(func(int) string)(n)})
	}
	execTemplate(buf, fmt.Sprintf("trailingFloat%d", bits), tmplTrailingFloat, rootData{Bits: bits, Cases: cases})
}

var tmplInterleavedFloat = `func registerFastFuncInterleavedFloat32x1(fn reflect.Value, cif *types.CallInterface, cfn uintptr, totalArgs, floatPos int, hasReturn bool) {
	switch totalArgs {
{{- range .}}
	case {{.TotalArgs}}:
		switch floatPos {
{{- range .Cases}}
		case {{.FloatPos}}:
			if hasReturn {
				impl := func({{.Params}}) uintptr {
					var ints [15]uintptr
					{{- range $i := seq .NumInts}}
					ints[{{$i}}] = a{{add $i 1}}
					{{- end}}
					var floats [8]uintptr
					floats[0] = uintptr(math.Float32bits(f1))
					return fastCallIF(cif, cfn, ints, floats)
				}
				forceFuncPtr(fn, &impl)
			} else {
				impl := func({{.Params}}) {
					var ints [15]uintptr
					{{- range $i := seq .NumInts}}
					ints[{{$i}}] = a{{add $i 1}}
					{{- end}}
					var floats [8]uintptr
					floats[0] = uintptr(math.Float32bits(f1))
					fastCallIF(cif, cfn, ints, floats)
				}
				forceFuncPtr(fn, &impl)
			}
{{- end}}
		}
{{- end}}
	}
}
`

func emitInterleavedFloat32x1(buf *bytes.Buffer) {
	type caseData struct {
		FloatPos int
		Params   string
		NumInts  int
	}
	type totalData struct {
		TotalArgs int
		Cases     []caseData
	}
	var groups []totalData
	for totalArgs := 2; totalArgs <= 15; totalArgs++ {
		var cases []caseData
		for floatPos := 0; floatPos <= totalArgs-2; floatPos++ {
			var parts []string
			intIdx := 1
			for i := 0; i < totalArgs; i++ {
				if i == floatPos {
					parts = append(parts, "f1 float32")
				} else {
					parts = append(parts, fmt.Sprintf("a%d uintptr", intIdx))
					intIdx++
				}
			}
			cases = append(cases, caseData{
				FloatPos: floatPos,
				Params:   strings.Join(parts, ", "),
				NumInts:  totalArgs - 1,
			})
		}
		groups = append(groups, totalData{TotalArgs: totalArgs, Cases: cases})
	}
	execTemplate(buf, "interleaved", tmplInterleavedFloat, groups)
}

var tmplTryRegisterFastPath = `func tryRegisterFastPath(fn reflect.Value, cif *types.CallInterface, cfn uintptr, ty reflect.Type) bool {
	if !((runtime.GOARCH == "amd64" || runtime.GOARCH == "arm64") && runtime.GOOS != "windows") {
		return false
	}
	numIn := ty.NumIn()
	if numIn > 15 {
		return false
	}

	var numFloats, numInts int
	trailingFloats := true
	seenFloat := false
	floatPos := -1

	for i := 0; i < numIn; i++ {
		switch ty.In(i).Kind() {
		case reflect.Uintptr, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
			reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Bool, reflect.Pointer, reflect.UnsafePointer:
			if seenFloat {
				trailingFloats = false
			}
			numInts++
		case reflect.Float32, reflect.Float64:
			if !seenFloat {
				floatPos = i
			}
			seenFloat = true
			numFloats++
		default:
			return false // Fallback for Structs, Arrays, Strings, Slices
		}
	}
	if numFloats > 8 || numInts > 15 {
		return false
	}

	hasReturn := ty.NumOut() > 0
	if hasReturn {
		switch ty.Out(0).Kind() {
		case reflect.Uintptr, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
			reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Bool, reflect.Pointer, reflect.UnsafePointer:
		case reflect.Float32, reflect.Float64:
			return false // Fast wrappers return uintptr, which uses a different ABI register class.
		default:
			return false
		}
	}

	if numFloats == 0 {
		registerFastFunc(fn, cif, cfn, numInts, hasReturn)
		return true
	}
	if numFloats == 1 && trailingFloats && ty.In(numInts).Kind() == reflect.Float32 {
		registerFastFuncFloat32x1(fn, cif, cfn, numInts, hasReturn)
		return true
	}
	if numFloats == 1 && trailingFloats && ty.In(numInts).Kind() == reflect.Float64 {
		registerFastFuncFloat64x1(fn, cif, cfn, numInts, hasReturn)
		return true
	}
	if numFloats == 1 && !trailingFloats && ty.In(floatPos).Kind() == reflect.Float32 {
		registerFastFuncInterleavedFloat32x1(fn, cif, cfn, numIn, floatPos, hasReturn)
		return true
	}

	return false
}
`
